# IMPORT

In [20]:
import os
import sys
import logging
import subprocess
import numpy as np
from shutil import copy
sys.path.insert(0, '/home/yongliang/third_party/merlin/src')
from io_funcs.binary_io import BinaryIOCollection
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# UTILITY

In [21]:
def get_file_list_of_dir(dir_path):
    res = [os.path.join(dir_path, f) for f in os.listdir(dir_path)]
    res.sort()
    return res

def gen_file_list(dir_path, file_id_list, ext):
    return [os.path.join(dir_path, f + '.' + ext) for f in file_id_list]

def get_file_id_list(file_list):
    return [os.path.splitext(os.path.basename(f))[0] for f in file_list]


io_funcs = BinaryIOCollection()

# CONFIGURATION


In [22]:
merlin_dir = '/home/yongliang/third_party/merlin'
silence_pattern = ['*-pau+*', '*-sil+*']
curr_dir = os.getcwd()
# hardcoded
nit_dir = os.path.join(curr_dir, 'nit')
wav_dir = os.path.join(nit_dir, 'wav2')
exp_dir = os.path.join(curr_dir, 'exp')
if not os.path.exists(exp_dir):
    os.makedirs(exp_dir)
lab_dir = os.path.join(exp_dir, 'lab')
orig_lab_file_list = get_file_list_of_dir(lab_dir)
file_id_list = get_file_id_list(orig_lab_file_list)

SPTK = {'VOPR': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/vopr', 
       'MGC2SP': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/mgc2sp', 
       'C2ACR': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/c2acr', 
       'FREQT': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/freqt', 
       'MC2B': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/mc2b', 
       'MLPG': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/mlpg', 
       'B2MC': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/b2mc', 
       'VSUM': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/vsum', 
       'MERGE': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/merge', 
       'SOPR': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/sopr', 
       'BCP': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/bcp', 
       'VSTAT': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/vstat', 
       'X2X': '/home/yongliang/third_party/merlin/tools/bin/SPTK-3.9/x2x'}
WORLD = {'SYNTHESIS': '/home/yongliang/third_party/merlin/tools/bin/WORLD/synth', 
        'ANALYSIS': '/home/yongliang/third_party/merlin/tools/bin/WORLD/analysis'}


# Prepare label files

In [23]:
hmm_dir = os.path.join(exp_dir, 'hmm')
full_dir = os.path.join(nit_dir, 'full')
mono_dir = os.path.join(nit_dir, 'mono')
phones = os.path.join(nit_dir, 'monophone')

In [15]:
from src.forced_alignment import ForcedAlignment

aligner = ForcedAlignment(hmm_dir, wav_dir, full_dir, mono_dir, phones, lab_dir)
aligner.prepare_training()
aligner.train_hmm(7, 32)
aligner.align()

---make file_id_list.scp: /home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/hmm/file_id_list.scp
---make copy.scp: /home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/hmm/config/copy.scp
---mfcc extraction at: /home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/hmm/mfc
------make copy.cfg: /home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/hmm/config/cfg
------extracting mfcc features...


KeyboardInterrupt: 

# Feature extraction

In [24]:
feat_dir = os.path.join(exp_dir, 'feat')
lf0_dir = os.path.join(feat_dir, 'lf0')
bap_dir = os.path.join(feat_dir, 'bap')
mgc_dir = os.path.join(feat_dir, 'mgc')
sample_rate = 16000

In [52]:
from src.feature_extraction import FeatureExtractor
feature_extractor = FeatureExtractor(wav_dir, sample_rate, feat_dir)
feature_extractor.extract_feat()


nitech_jp_song070_f001_003
Running REAPER f0 extraction...


KeyboardInterrupt: 


nitech_jp_song070_f001_004
Running REAPER f0 extraction...

nitech_jp_song070_f001_007
Running REAPER f0 extraction...

nitech_jp_song070_f001_010
Running REAPER f0 extraction...

nitech_jp_song070_f001_012
Running REAPER f0 extraction...

nitech_jp_song070_f001_014
Running REAPER f0 extraction...

nitech_jp_song070_f001_015
Running REAPER f0 extraction...

nitech_jp_song070_f001_016
Running REAPER f0 extraction...

nitech_jp_song070_f001_019
Running REAPER f0 extraction...

nitech_jp_song070_f001_020
Running REAPER f0 extraction...

nitech_jp_song070_f001_021
Running REAPER f0 extraction...

nitech_jp_song070_f001_022
Running REAPER f0 extraction...

nitech_jp_song070_f001_023
Running REAPER f0 extraction...

nitech_jp_song070_f001_025
Running REAPER f0 extraction...

nitech_jp_song070_f001_028
Running REAPER f0 extraction...

nitech_jp_song070_f001_029
Running REAPER f0 extraction...

nitech_jp_song070_f001_030
Running REAPER f0 extraction...

nitech_jp_song070_f001_037
Running REAP

Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt


# Duration model

## Model configuration

In [25]:
# duration model related

# hardcoded
dur_lab_dim = 368
dur_cmp_dim = 5
dur_train_file_number = 27
dur_valid_file_number = 1
dur_test_file_number = 1

dur_mdl_dir = os.path.join(exp_dir, 'duration_model')
if not os.path.exists(dur_mdl_dir):
    os.makedirs(dur_mdl_dir)

dur_tmp_dir = os.path.join(dur_mdl_dir, 'tmp')
if not os.path.exists(dur_tmp_dir):
    os.makedirs(dur_tmp_dir)
    
dur_inter_dir = os.path.join(dur_mdl_dir, 'inter')
if not os.path.exists(dur_inter_dir):
    os.makedirs(dur_inter_dir)

dur_lab_dir = os.path.join(dur_inter_dir, 'lab_' + str(dur_lab_dim))
if not os.path.exists(dur_lab_dir):
    os.makedirs(dur_lab_dir)
    
dur_lab_no_silence_dir = os.path.join(dur_inter_dir, 'lab_no_silence_' + str(dur_lab_dim))
if not os.path.exists(dur_lab_no_silence_dir):
    os.makedirs(dur_lab_no_silence_dir)
    
dur_lab_no_silence_norm_dir = os.path.join(dur_inter_dir, 'lab_no_silence_norm_' + str(dur_lab_dim))
if not os.path.exists(dur_lab_no_silence_norm_dir):
    os.makedirs(dur_lab_no_silence_norm_dir)

dur_dur_dir = os.path.join(dur_inter_dir, 'dur')
if not os.path.exists(dur_dur_dir):
    os.makedirs(dur_dur_dir)
    
dur_cmp_dir = os.path.join(dur_inter_dir, 'cmp_' + str(dur_cmp_dim))
if not os.path.exists(dur_cmp_dir):
    os.makedirs(dur_cmp_dir)
    
dur_cmp_no_silence_dir = os.path.join(dur_inter_dir, 'cmp_no_silence_' + str(dur_cmp_dim))
if not os.path.exists(dur_cmp_no_silence_dir):
    os.makedirs(dur_cmp_no_silence_dir)
    
dur_cmp_no_silence_norm_dir = os.path.join(dur_inter_dir, 'cmp_no_silence_norm_' + str(dur_cmp_dim))
if not os.path.exists(dur_cmp_no_silence_norm_dir):
    os.makedirs(dur_cmp_no_silence_norm_dir)
    
dur_variance_dir = os.path.join(dur_inter_dir, 'variance')
if not os.path.exists(dur_variance_dir):
    os.makedirs(dur_variance_dir)
    
dur_nn_mdl_dir = os.path.join(dur_mdl_dir, 'mdl')
if not os.path.exists(dur_nn_mdl_dir):
    os.makedirs(dur_nn_mdl_dir)
    
    

dur_lab_norm_file = os.path.join(dur_inter_dir, 'lab_norm_' + str(dur_lab_dim) + '.dat')
dur_cmp_norm_file = os.path.join(dur_inter_dir, 'cmp_norm_' + str(dur_cmp_dim) + '.dat')

dur_dur_var_file = os.path.join(dur_variance_dir, 'dur')

    
dur_lab_file_list = gen_file_list(dur_lab_dir, file_id_list, 'labbin')
dur_lab_no_silence_file_list = gen_file_list(dur_lab_no_silence_dir, file_id_list, 'labbin')
dur_lab_no_silence_norm_file_list = gen_file_list(dur_lab_no_silence_norm_dir, file_id_list, 'labbin')
dur_dur_file_list = gen_file_list(dur_dur_dir, file_id_list, 'dur')
dur_cmp_file_list = gen_file_list(dur_cmp_dir, file_id_list, 'cmp')
dur_cmp_no_silence_file_list = gen_file_list(dur_cmp_no_silence_dir, file_id_list, 'cmp')
dur_cmp_no_silence_norm_file_list = gen_file_list(dur_cmp_no_silence_norm_dir, file_id_list, 'cmp')

## Feature extraction from label files

In [26]:
ques_dir = os.path.join(curr_dir, 'ques')
question = os.path.join(ques_dir, 'general')

In [27]:
from frontend.label_normalisation import HTSLabelNormalisation
dur_lab_normaliser = HTSLabelNormalisation(question, add_frame_features=False, subphone_feats='none')
dur_lab_normaliser.perform_normalisation(orig_lab_file_list, dur_lab_file_list)

## Remove silence phone

In [28]:
from frontend.silence_remover import SilenceRemover
dur_silence_remover = SilenceRemover(n_cmp=dur_lab_dim, silence_pattern=silence_pattern, remove_frame_features=False, subphone_feats='none')
dur_silence_remover.remove_silence(dur_lab_file_list, orig_lab_file_list, dur_lab_no_silence_file_list)

In [29]:
_, num_frame = io_funcs.load_binary_file_frame(dur_lab_file_list[2], 368)
_, num_frame_nn = io_funcs.load_binary_file_frame(dur_lab_no_silence_file_list[2], 368)
print(num_frame)
print(num_frame_nn)

131
124


In [30]:
tmp, _ = io_funcs.load_binary_file_frame(dur_lab_file_list[2], 368)
print(tmp)

[[  0.   0.   0. ...  -1.  -1.  -1.]
 [  0.   0.   0. ...  -1.  -1.  -1.]
 [  0.   0.   0. ... 192.   0. 100.]
 ...
 [  0.   0.   0. ...  72.  57.  43.]
 [  0.   0.   0. ...  -1.  -1.  -1.]
 [  0.   0.   0. ...  -1.  -1.  -1.]]


## Input feature normalization

In [31]:
from frontend.min_max_norm import MinMaxNormalisation
dur_min_max_normaliser = MinMaxNormalisation(feature_dimension=dur_lab_dim, min_value=0.01, max_value=0.99)
dur_min_max_normaliser.find_min_max_values(dur_lab_no_silence_file_list[0: dur_train_file_number])
dur_min_max_normaliser.normalise_data(dur_lab_no_silence_file_list, dur_lab_no_silence_norm_file_list)
dur_label_min_vector = dur_min_max_normaliser.min_vector
dur_label_max_vector = dur_min_max_normaliser.max_vector
dur_label_norm_info = np.concatenate((dur_label_min_vector, dur_label_max_vector), axis=0)
dur_label_norm_info = np.array(dur_label_norm_info, 'float32')
fid = open(dur_lab_norm_file, 'wb')
dur_label_norm_info.tofile(fid)
fid.close()

In [32]:
dur_label_norm_info.shape

(2, 368)

## Compute duration from label files

In [33]:
dur_lab_normaliser.prepare_dur_data(orig_lab_file_list, dur_dur_file_list, feature_type='numerical')

In [34]:
feat, num_frame = io_funcs.load_binary_file_frame(dur_dur_file_list[0], 5)
print(feat.shape)
print(num_frame)
print(feat[0:10, :])

(151, 5)
151
[[  1. 161.  34.  18.  22.]
 [  2.   2.   2.   1.   1.]
 [  2.   1.  66.   7.   3.]
 [  5.  10.   1.   1.  15.]
 [  2.   5.   2.   1.   1.]
 [  4.   1.  32.   4.   5.]
 [  6.   1.  27.  20.   1.]
 [  1.   6.   2.   1.   2.]
 [  1.  54.   1.   1.   2.]
 [ 10.   9.   4.   2.   4.]]


In [35]:
dur_dur_file_list[2]

'/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/duration_model/inter/dur/nitech_jp_song070_f001_007.dur'

## Make output features for duration model

In [36]:
delta_win = [-0.5, 0.0, 0.5]
acc_win = [1.0, -2.0, 1.0]
"""
"in" & "out" just mean before & after feature composition 
like if we compute dynamic features, dimensions of out will be 3 times of in
not really mean in & out of the network 
""" 
dur_in_dimension_dict = {'dur': 5} 
dur_out_dimension_dict = {'dur': 5}
dur_in_file_list_dict = {'dur': dur_dur_file_list}

In [37]:
from frontend.acoustic_composition import AcousticComposition
dur_acoustic_worker = AcousticComposition(delta_win = delta_win, acc_win = acc_win)
dur_acoustic_worker.prepare_nn_data(dur_in_file_list_dict, dur_cmp_file_list, dur_in_dimension_dict, dur_out_dimension_dict)

In [19]:
feat, num_frame = io_funcs.load_binary_file_frame(dur_cmp_file_list[2], 5)
print(feat.shape)
print(num_frame)
print(feat[0:10, :])

(131, 5)
131
[[ 13.  72. 166.   2.  54.]
 [  9.  47.   1.  54.  32.]
 [  1.  18.   4.   4.   4.]
 [  3. 100.   1.   2.   6.]
 [  4.   5.   3.   3.   3.]
 [  1.  32.   1.   1.   3.]
 [  5.   3.   2.   2.   3.]
 [  2.  26.   1.   5.   8.]
 [  2.   3.   3.   7.   6.]
 [  6.  77.  17.   5.   5.]]


## Remove silence phone

In [38]:
dur_silence_remover = SilenceRemover(n_cmp = dur_cmp_dim, silence_pattern = silence_pattern, remove_frame_features = False, subphone_feats = 'none')
dur_silence_remover.remove_silence(dur_cmp_file_list, orig_lab_file_list, dur_cmp_no_silence_file_list) 

In [39]:
_, num_frame = io_funcs.load_binary_file_frame(dur_cmp_file_list[2], 5)
_, num_frame_nn = io_funcs.load_binary_file_frame(dur_cmp_no_silence_file_list[2], 5)
print(num_frame)
print(num_frame_nn)

131
124


## Output feature (duration) normalization

In [40]:
from frontend.mean_variance_norm import MeanVarianceNorm
dur_mvn_normaliser = MeanVarianceNorm(feature_dimension=dur_cmp_dim)
dur_global_mean_vector = dur_mvn_normaliser.compute_mean(dur_cmp_no_silence_file_list[0: dur_train_file_number], 0, dur_cmp_dim)
dur_global_std_vector = dur_mvn_normaliser.compute_std(dur_cmp_no_silence_file_list[0: dur_train_file_number], dur_global_mean_vector, 0, dur_cmp_dim)
dur_mvn_normaliser.feature_normalisation(dur_cmp_no_silence_file_list, dur_cmp_no_silence_norm_file_list)
dur_cmp_norm_info = np.concatenate((dur_global_mean_vector, dur_global_std_vector), axis=0)
dur_cmp_norm_info = np.array(dur_cmp_norm_info, 'float32')
fid = open(dur_cmp_norm_file, 'wb')
dur_cmp_norm_info.tofile(fid)
fid.close()

In [41]:
tmp1, num1 = io_funcs.load_binary_file_frame(dur_cmp_no_silence_file_list[0], 5)
tmp2, num2 = io_funcs.load_binary_file_frame(dur_cmp_no_silence_norm_file_list[0], 5)
print(num1 == num2)
print(tmp2)

True
[[-0.7233047  -0.43827328 -0.4121524  -0.33808738 -0.66881937]
 [-0.7233047  -0.46908876  1.6973542  -0.10570705 -0.3786838 ]
 [-0.09544833 -0.19174956 -0.44511345 -0.33808738  1.3621298 ]
 [-0.7233047  -0.3458269  -0.4121524  -0.33808738 -0.66881937]
 [-0.30473378 -0.46908876  0.5766788  -0.22189721 -0.0885482 ]
 [ 0.11383712 -0.46908876  0.4118736   0.3977837  -0.66881937]
 [-0.9325901  -0.3150114  -0.4121524  -0.33808738 -0.5237516 ]
 [-0.9325901   1.164131   -0.44511345 -0.33808738 -0.5237516 ]
 [ 0.95097893 -0.22256503 -0.34623033 -0.29935732 -0.233616  ]
 [-0.9325901  -0.46908876 -0.4121524  -0.29935732 -0.0885482 ]
 [ 0.11383712 -0.37664235 -0.44511345 -0.33808738 -0.5237516 ]
 [-0.30473378  0.39374432 -0.44511345 -0.33808738 -0.233616  ]
 [ 0.95097893 -0.16093409 -0.34623033 -0.26062727 -0.3786838 ]
 [-0.7233047  -0.46908876  0.4118736  -0.33808738  0.3466552 ]
 [ 0.11383712 -0.37664235 -0.37919137 -0.29935732 -0.3786838 ]
 [-0.51401925 -0.46908876  1.4336659  -0.29935732 

In [42]:
dur_cmp_norm_info.shape

(2, 5)

In [43]:
dur_variance_file_dict = {'dur': dur_dur_var_file}

In [44]:
feat_ind = 0
for feat in list(dur_out_dimension_dict.keys()):
    feat_std_vector = np.array(dur_global_std_vector[:, feat_ind: feat_ind + dur_out_dimension_dict[feat]], 'float32')
    fid = open(dur_variance_file_dict[feat], 'w')
    feat_var_vector = feat_std_vector**2
    feat_var_vector.tofile(fid)
    fid.close()
    feat_ind += dur_out_dimension_dict[feat]

In [45]:
print(dur_global_std_vector)
print(feat_var_vector)

[[ 4.77816306 32.451236   30.33884862 25.81974051  6.89332861]]
[[  22.830841 1053.0828    920.4457    666.659      47.51798 ]]


## Model training

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils.data as data
from torch.autograd import Variable
import math

import matplotlib.pyplot as plt

In [7]:
class DurationDataset(data.Dataset):
    def __init__(self, lab_file_list, cmp_file_list, lab_dim=368, cmp_dim=5):
        assert(len(lab_file_list) == len(cmp_file_list))
        for i in range(len(lab_file_list)):
            lab_basename = os.path.splitext(os.path.basename(lab_file_list[i]))[0]
            cmp_basename = os.path.splitext(os.path.basename(cmp_file_list[i]))[0]
#             print(lab_basename)
#             print(cmp_basename)
#             print('*' * 20)
            assert lab_basename == cmp_basename
        self.lab_file_list = lab_file_list
        self.cmp_file_list = cmp_file_list
        self.lab_dim = lab_dim
        self.cmp_dim = cmp_dim
        self.io_funcs = BinaryIOCollection()
        
    def __len__(self):
        return len(self.lab_file_list)
    
    def __getitem__(self, ind):
        X = torch.from_numpy(self.io_funcs.load_binary_file_frame(self.lab_file_list[ind], self.lab_dim)[0])
        Y = torch.from_numpy(self.io_funcs.load_binary_file_frame(self.cmp_file_list[ind], self.cmp_dim)[0])
        
        return X, Y

In [8]:
def collate_fn(batch):
    def func(p):
        return p[0].size(0)
    
    batch_size = len(batch)
    
    max_seq_len = max(batch, key=func)[0].size(0)
    min_seq_len = min(batch, key=func)[0].size(0)
    
    lab_dim = batch[0][0].size(1)
    cmp_dim = batch[0][1].size(1)
    

    
    
    if max_seq_len <= 2 * min_seq_len:
        sample_len = int(min_seq_len/2)
    else:
        sample_len = min_seq_len
    
    
    total_sample_num = 0
    for i in range(batch_size):
        lab = batch[i][0]
        cmp = batch[i][1]
        num_seq = math.ceil(lab.size(0)/sample_len)
        total_sample_num += num_seq


    
    labs = torch.zeros(total_sample_num, sample_len, lab_dim)
    cmps = torch.zeros(total_sample_num, sample_len, cmp_dim)
    
    curr_sample_ind = 0
    for i in range(batch_size):
        ind_in_file = 0
        for j in range(math.floor(batch[i][0].size(0)/sample_len)):
            labs[curr_sample_ind].copy_(batch[i][0][ind_in_file * sample_len: (ind_in_file+1) * sample_len][:])
            cmps[curr_sample_ind].copy_(batch[i][1][ind_in_file * sample_len: (ind_in_file+1) * sample_len][:])
            ind_in_file += 1
            curr_sample_ind += 1
        if batch[i][0].size(0) % sample_len != 0:
            labs[curr_sample_ind].copy_(batch[i][0][-sample_len:][:])
            cmps[curr_sample_ind].copy_(batch[i][1][-sample_len:][:])
            curr_sample_ind += 1
    
    assert(curr_sample_ind == total_sample_num)
    
#     print("lab dimension: " + str(lab_dim))
#     print("cmp dimension: " + str(cmp_dim))
#     seq_len_list = [i[0].size(0) for i in batch]
#     print("sequence length for each file: " + str(seq_len_list))
#     print('max sequence length of original file: ', str(max_seq_len))
#     print('min sequence length of original file: ', str(min_seq_len))
#     print("sample length: ", str(sample_len))
#     print('total_sample_num: ' + str(total_sample_num))
    
#     torch.set_printoptions(profile="full")
#     print(batch[0][1])
#     print(cmps)
#     torch.set_printoptions(profile="default")
    
    return labs, cmps, sample_len

In [9]:
class DurationModel(nn.Module):
    def __init__(self, dur_lab_dim, dur_cmp_dim):
        super(DurationModel, self).__init__()
        
        self.fc1 = nn.Linear(dur_lab_dim, 512)
        self.fc2 = nn.Linear(512, 512)
        self.fc3 = nn.Linear(512, 512)
        self.fc4 = nn.Linear(512, 512)
#         self.fc4 = nn.Linear(512, dur_cmp_dim)
        self.fc5 = nn.Linear(512, dur_cmp_dim)
        
    def forward(self, dur_lab):
        res = F.relu(self.fc1(dur_lab))
        res = F.relu(self.fc2(res))
        res = F.relu(self.fc3(res))
#         res = self.fc4(res)
        res = F.relu(self.fc4(res))
        res = self.fc5(res)
        return res

In [10]:
def train(model, train_loader, valid_loader, epoch):
    model.train()
    for batch_ind, batch in enumerate(train_loader):
        lab, cmp = Variable(batch[0]), Variable(batch[1])
        loss = criterion(model(lab), cmp)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if batch_ind % log_interval == 0:
            val_loss = evaluate(model, valid_loader)
            train_loss = loss.item()
            epoch_progress = 100. * batch_ind / len(train_loader)
            print('Train Epoch: {}({:.0f}%)\tTrain Loss: {:.6f}\tVal Loss: {:.6f}'.format(
                epoch, epoch_progress, train_loss, val_loss))
            
            
def evaluate(model, valid_loader):
    model.eval()
    total_loss = 0
    n_examples = 0
    for batch_ind, batch in enumerate(valid_loader):
        lab, cmp, sample_len = Variable(batch[0], volatile=True), Variable(batch[1]), batch[2]
        output = model(lab)
        loss = criterion(output, cmp, size_average=False).item()
#         print('loss without average: ' + str(loss))
        total_loss += loss
        n = len(lab)
#         print('num samples this batch: ' + str(n))
#         print(cmp.size())
        n_examples += n
    
    total_loss /= (n_examples * sample_len * cmp.size()[-1])
    return total_loss

In [11]:
# TODO to implement cross-validation, print something here to see whether could do normalisation in Pytorch
batch_size = int(dur_train_file_number)
# batch_size = 1
# dur_train_set = DurationDataset([dur_lab_no_silence_norm_file_list[0]] * dur_train_file_number, 
#                                 [dur_cmp_no_silence_norm_file_list[0]] * dur_train_file_number)
# dur_valid_set = DurationDataset(dur_lab_no_silence_norm_file_list[dur_train_file_number: dur_train_file_number + dur_valid_file_number],
#                                 dur_cmp_no_silence_norm_file_list[dur_train_file_number: dur_train_file_number + dur_valid_file_number])
dur_train_set = DurationDataset(dur_lab_no_silence_norm_file_list[:dur_train_file_number], dur_cmp_no_silence_norm_file_list[:dur_train_file_number])
dur_valid_set = DurationDataset(dur_lab_no_silence_norm_file_list[:dur_valid_file_number], dur_cmp_no_silence_norm_file_list[:dur_valid_file_number])
dur_train_loader = data.DataLoader(dur_train_set, shuffle=False, batch_size=batch_size, collate_fn=collate_fn)
dur_valid_loader = data.DataLoader(dur_valid_set, shuffle=False, batch_size=dur_valid_file_number, collate_fn=collate_fn)

tmp = next(iter(dur_train_loader))
lab_, cmp_, _ = tmp
print(lab_.size())
print(cmp_.size())
print(len(lab_))
print(len(Variable(lab_)))
print(len(dur_valid_set))

NameError: name 'dur_train_file_number' is not defined

In [42]:
lr = 0.001
log_interval = 1
epochs = 100
duration_model = nn.Sequential(
    nn.Linear(dur_lab_dim, 512),
    nn.Dropout(0.5),
    nn.ReLU(),
    nn.Linear(512, 512),
    nn.Dropout(0.5),
    nn.ReLU(),
    nn.Linear(512, 512),
    nn.Dropout(0.5),
    nn.ReLU(),
    nn.Linear(512, 512),
    nn.Dropout(0.5),
    nn.ReLU(),
    nn.Linear(512, dur_cmp_dim)
)
print(duration_model)
optimizer = torch.optim.Adam(duration_model.parameters(), lr=lr)
criterion = F.mse_loss
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[90], gamma=0.01)
for epoch in range(1, epochs+1):
    scheduler.step()
    train(duration_model, dur_train_loader, dur_valid_loader, epoch)

Sequential(
  (0): Linear(in_features=368, out_features=512, bias=True)
  (1): Dropout(p=0.5)
  (2): ReLU()
  (3): Linear(in_features=512, out_features=512, bias=True)
  (4): Dropout(p=0.5)
  (5): ReLU()
  (6): Linear(in_features=512, out_features=512, bias=True)
  (7): Dropout(p=0.5)
  (8): ReLU()
  (9): Linear(in_features=512, out_features=512, bias=True)
  (10): Dropout(p=0.5)
  (11): ReLU()
  (12): Linear(in_features=512, out_features=5, bias=True)
)


/home/yongliang/venv3/lib/python3.5/site-packages/ipykernel_launcher.py:22: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.


Train Epoch: 1(0%)	Train Loss: 1.015382	Val Loss: 0.419610
Train Epoch: 2(0%)	Train Loss: 1.010938	Val Loss: 0.411266
Train Epoch: 3(0%)	Train Loss: 1.006758	Val Loss: 0.399702
Train Epoch: 4(0%)	Train Loss: 0.998417	Val Loss: 0.385279
Train Epoch: 5(0%)	Train Loss: 0.984328	Val Loss: 0.376172
Train Epoch: 6(0%)	Train Loss: 0.969366	Val Loss: 0.382484
Train Epoch: 7(0%)	Train Loss: 0.957654	Val Loss: 0.402373
Train Epoch: 8(0%)	Train Loss: 0.961003	Val Loss: 0.406695
Train Epoch: 9(0%)	Train Loss: 0.959084	Val Loss: 0.397913
Train Epoch: 10(0%)	Train Loss: 0.951252	Val Loss: 0.386501
Train Epoch: 11(0%)	Train Loss: 0.942314	Val Loss: 0.380220
Train Epoch: 12(0%)	Train Loss: 0.938326	Val Loss: 0.372340
Train Epoch: 13(0%)	Train Loss: 0.930071	Val Loss: 0.362142
Train Epoch: 14(0%)	Train Loss: 0.918603	Val Loss: 0.350061
Train Epoch: 15(0%)	Train Loss: 0.902814	Val Loss: 0.339645
Train Epoch: 16(0%)	Train Loss: 0.880264	Val Loss: 0.329850
Train Epoch: 17(0%)	Train Loss: 0.857533	Val Loss

In [34]:
lr = 0.25
log_interval = 1
epochs = 200
duration_model = DurationModel(dur_lab_dim, dur_cmp_dim)
print(duration_model)
optimizer = torch.optim.SGD(duration_model.parameters(), lr=lr)
criterion = F.mse_loss
for epoch in range(1, epochs+1):
    train(duration_model, dur_train_loader, dur_valid_loader, epoch)

DurationModel(
  (fc1): Linear(in_features=368, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=512, bias=True)
  (fc4): Linear(in_features=512, out_features=512, bias=True)
  (fc5): Linear(in_features=512, out_features=5, bias=True)
)


/home/yongliang/venv3/lib/python3.5/site-packages/ipykernel_launcher.py:22: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
/home/yongliang/venv3/lib/python3.5/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


Train Epoch: 1(0%)	Train Loss: 1.014548	Val Loss: 0.423275
Train Epoch: 2(0%)	Train Loss: 1.014099	Val Loss: 0.422601
Train Epoch: 3(0%)	Train Loss: 1.013744	Val Loss: 0.422045
Train Epoch: 4(0%)	Train Loss: 1.013454	Val Loss: 0.421579
Train Epoch: 5(0%)	Train Loss: 1.013213	Val Loss: 0.421185
Train Epoch: 6(0%)	Train Loss: 1.013007	Val Loss: 0.420850
Train Epoch: 7(0%)	Train Loss: 1.012827	Val Loss: 0.420562
Train Epoch: 8(0%)	Train Loss: 1.012666	Val Loss: 0.420310
Train Epoch: 9(0%)	Train Loss: 1.012519	Val Loss: 0.420087
Train Epoch: 10(0%)	Train Loss: 1.012381	Val Loss: 0.419888
Train Epoch: 11(0%)	Train Loss: 1.012249	Val Loss: 0.419706
Train Epoch: 12(0%)	Train Loss: 1.012122	Val Loss: 0.419539
Train Epoch: 13(0%)	Train Loss: 1.011996	Val Loss: 0.419382
Train Epoch: 14(0%)	Train Loss: 1.011870	Val Loss: 0.419234
Train Epoch: 15(0%)	Train Loss: 1.011744	Val Loss: 0.419093
Train Epoch: 16(0%)	Train Loss: 1.011618	Val Loss: 0.418957
Train Epoch: 17(0%)	Train Loss: 1.011491	Val Loss

Train Epoch: 138(0%)	Train Loss: 0.920938	Val Loss: 0.444590
Train Epoch: 139(0%)	Train Loss: 1.091513	Val Loss: 0.367362
Train Epoch: 140(0%)	Train Loss: 0.895048	Val Loss: 0.333956
Train Epoch: 141(0%)	Train Loss: 0.883293	Val Loss: 0.342094
Train Epoch: 142(0%)	Train Loss: 0.873264	Val Loss: 0.323039
Train Epoch: 143(0%)	Train Loss: 0.872296	Val Loss: 0.347677
Train Epoch: 144(0%)	Train Loss: 0.875028	Val Loss: 0.332793
Train Epoch: 145(0%)	Train Loss: 0.902637	Val Loss: 0.369085
Train Epoch: 146(0%)	Train Loss: 0.893660	Val Loss: 0.347921
Train Epoch: 147(0%)	Train Loss: 0.938882	Val Loss: 0.334252
Train Epoch: 148(0%)	Train Loss: 0.863919	Val Loss: 0.318959
Train Epoch: 149(0%)	Train Loss: 0.858907	Val Loss: 0.328029
Train Epoch: 150(0%)	Train Loss: 0.856649	Val Loss: 0.316592
Train Epoch: 151(0%)	Train Loss: 0.863284	Val Loss: 0.346755
Train Epoch: 152(0%)	Train Loss: 0.872251	Val Loss: 0.338869
Train Epoch: 153(0%)	Train Loss: 0.919249	Val Loss: 0.336343
Train Epoch: 154(0%)	Tra

In [43]:
dur_nn_mdl_file = os.path.join(dur_nn_mdl_dir, 'dur_nn_mdl.pt')
torch.save(duration_model.state_dict(), dur_nn_mdl_file)

## Test

In [17]:
print('files for test: ')
print(dur_lab_no_silence_norm_file_list[-1])
print(dur_cmp_no_silence_norm_file_list[-1])
print(dur_cmp_no_silence_file_list[-1])
print('*' * 20)




input_lab, num_input_frame = io_funcs.load_binary_file_frame(dur_lab_no_silence_norm_file_list[-1], 368)
target_cmp, num_target_frame = io_funcs.load_binary_file_frame(dur_cmp_no_silence_norm_file_list[-1], 5)
assert(num_input_frame == num_target_frame)
print('target output cmp: ')
print(target_cmp[:10, :])

input_lab = torch.from_numpy(input_lab)
input_lab = input_lab[None, :, :]
output_cmp = duration_model(input_lab)
assert(output_cmp.size()[1] == num_target_frame)
print('output cmp: ')
print(output_cmp[0].detach().numpy()[:10, :])

target_dur, num_dur_frame = io_funcs.load_binary_file_frame(dur_cmp_no_silence_file_list[-1], 5)
assert(num_dur_frame == num_target_frame)
print('target dur: ')
print(target_dur[:10, :])

fid = open(dur_cmp_norm_file, 'rb')
dur_cmp_norm_info = np.fromfile(fid, dtype=np.float32)
fid.close()
dur_cmp_norm_info = dur_cmp_norm_info.reshape(2, -1)
dur_cmp_mean = dur_cmp_norm_info[0, ]
dur_cmp_std = dur_cmp_norm_info[1, ]

test_tmp_file = os.path.join(dur_tmp_dir, 'dur_output.cmp')
output_cmp = output_cmp.detach().numpy()[0]
io_funcs.array_to_binary_file(output_cmp, test_tmp_file)

print('mean: ', dur_cmp_mean)
print('std: ', dur_cmp_std)

test_dur_denormaliser = MeanVarianceNorm(feature_dimension=dur_cmp_dim)
test_dur_denormaliser.feature_denormalisation([test_tmp_file], [test_tmp_file], dur_cmp_mean, dur_cmp_std)
pred_dur = io_funcs.load_binary_file_frame(test_tmp_file, 5)
print('predicted dur: ')
print(type(pred_dur))
print(pred_dur[0][:10, :])

files for test: 


NameError: name 'dur_lab_no_silence_norm_file_list' is not defined

# Acoustic model

## Model configuration

In [46]:
# acoustic model related

# hardcoded
acou_lab_dim = 377
acou_cmp_dim = 187
acou_train_file_number = 27
acou_valid_file_number = 1
acou_test_file_number = 1

acou_mdl_dir = os.path.join(exp_dir, 'acoustic_model')
if not os.path.exists(acou_mdl_dir):
    os.makedirs(acou_mdl_dir)
    
acou_inter_dir = os.path.join(acou_mdl_dir, 'inter')
if not os.path.exists(acou_inter_dir):
    os.makedirs(acou_inter_dir)

acou_lab_dir = os.path.join(acou_inter_dir, 'lab_' + str(acou_lab_dim))
if not os.path.exists(acou_lab_dir):
    os.makedirs(acou_lab_dir)
    
acou_lab_no_silence_dir = os.path.join(acou_inter_dir, 'lab_no_silence_' + str(acou_lab_dim))
if not os.path.exists(acou_lab_no_silence_dir):
    os.makedirs(acou_lab_no_silence_dir)
    
acou_lab_no_silence_norm_dir = os.path.join(acou_inter_dir, 'lab_no_silence_norm_' + str(acou_lab_dim))
if not os.path.exists(acou_lab_no_silence_norm_dir):
    os.makedirs(acou_lab_no_silence_norm_dir)

'''
acou_dur_dir = os.path.join(acou_inter_dir, 'dur')
if not os.path.exists(acou_dur_dir):
    os.makedirs(acou_dur_dir)
'''

    
acou_cmp_dir = os.path.join(acou_inter_dir, 'cmp_' + str(acou_cmp_dim))
if not os.path.exists(acou_cmp_dir):
    os.makedirs(acou_cmp_dir)
    
acou_cmp_no_silence_dir = os.path.join(acou_inter_dir, 'cmp_no_silence_' + str(acou_cmp_dim))
if not os.path.exists(acou_cmp_no_silence_dir):
    os.makedirs(acou_cmp_no_silence_dir)
    
acou_cmp_no_silence_norm_dir = os.path.join(acou_inter_dir, 'cmp_no_silence_norm_' + str(acou_cmp_dim))
if not os.path.exists(acou_cmp_no_silence_norm_dir):
    os.makedirs(acou_cmp_no_silence_norm_dir)
    
acou_variance_dir = os.path.join(acou_inter_dir, 'variance')
if not os.path.exists(acou_variance_dir):
    os.makedirs(acou_variance_dir)
    
acou_nn_mdl_dir = os.path.join(acou_mdl_dir, 'mdl')
if not os.path.exists(acou_nn_mdl_dir):
    os.makedirs(acou_nn_mdl_dir)
    
    

acou_lab_norm_file = os.path.join(acou_inter_dir, 'lab_norm_' + str(acou_lab_dim) + '.dat')
acou_cmp_norm_file = os.path.join(acou_inter_dir, 'cmp_norm_' + str(acou_cmp_dim) + '.dat')

acou_vuv_var_file = os.path.join(acou_variance_dir, 'vuv')
acou_mgc_var_file = os.path.join(acou_variance_dir, 'mgc')
acou_lf0_var_file = os.path.join(acou_variance_dir, 'lf0')
acou_bap_var_file = os.path.join(acou_variance_dir, 'bap')
    
acou_lab_file_list = gen_file_list(acou_lab_dir, file_id_list, 'labbin')
acou_lab_no_silence_file_list = gen_file_list(acou_lab_no_silence_dir, file_id_list, 'labbin')
acou_lab_no_silence_norm_file_list = gen_file_list(acou_lab_no_silence_norm_dir, file_id_list, 'labbin')
# dur_dur_file_list = gen_file_list(dur_dur_dir, file_id_list, 'dur')
acou_cmp_file_list = gen_file_list(acou_cmp_dir, file_id_list, 'cmp')
acou_cmp_no_silence_file_list = gen_file_list(acou_cmp_no_silence_dir, file_id_list, 'cmp')
acou_cmp_no_silence_norm_file_list = gen_file_list(acou_cmp_no_silence_norm_dir, file_id_list, 'cmp')


acou_lf0_file_list = gen_file_list(lf0_dir, file_id_list, 'lf0')
acou_mgc_file_list = gen_file_list(mgc_dir, file_id_list, 'mgc')
acou_bap_file_list = gen_file_list(bap_dir, file_id_list, 'bap')

## Feature extraction from label files

In [47]:
acou_lab_normaliser = HTSLabelNormalisation(question, add_frame_features=True, subphone_feats='full')
acou_lab_normaliser.perform_normalisation(orig_lab_file_list, acou_lab_file_list)

## Remove silence phone

In [48]:
acou_silence_remover = SilenceRemover(n_cmp=acou_lab_dim, silence_pattern=silence_pattern, remove_frame_features=True, subphone_feats='full')
acou_silence_remover.remove_silence(acou_lab_file_list, orig_lab_file_list, acou_lab_no_silence_file_list)

In [49]:
_, num_frame = io_funcs.load_binary_file_frame(acou_lab_file_list[2], 377)
_, num_frame_nn = io_funcs.load_binary_file_frame(acou_lab_no_silence_file_list[2], 377)
print(num_frame)
print(num_frame_nn)

8635
7201


In [50]:
tmp, _ = io_funcs.load_binary_file_frame(acou_lab_file_list[2], 377)
print(tmp)

[[0.         0.         0.         ... 0.04234528 1.         0.00325733]
 [0.         0.         0.         ... 0.04234528 0.99674267 0.00651466]
 [0.         0.         0.         ... 0.04234528 0.99348533 0.00977199]
 ...
 [0.         0.         0.         ... 0.2925373  0.00895522 0.9940299 ]
 [0.         0.         0.         ... 0.2925373  0.00597015 0.99701494]
 [0.         0.         0.         ... 0.2925373  0.00298507 1.        ]]


## Input feature normalization

In [51]:
acou_min_max_normaliser = MinMaxNormalisation(feature_dimension=acou_lab_dim, min_value=0.01, max_value=0.99)
acou_min_max_normaliser.find_min_max_values(acou_lab_no_silence_file_list[0: acou_train_file_number])
acou_min_max_normaliser.normalise_data(acou_lab_no_silence_file_list, acou_lab_no_silence_norm_file_list)
acou_label_min_vector = acou_min_max_normaliser.min_vector
acou_label_max_vector = acou_min_max_normaliser.max_vector
acou_label_norm_info = np.concatenate((acou_label_min_vector, acou_label_max_vector), axis=0)
acou_label_norm_info = np.array(acou_label_norm_info, 'float32')
fid = open(acou_lab_norm_file, 'wb')
acou_label_norm_info.tofile(fid)
fid.close()

In [52]:
acou_label_norm_info.shape

(2, 377)

## Make output features for acoustic model

In [53]:
"""
"in" & "out" just mean before & after feature composition 
like if we compute dynamic features, dimensions of out will be 3 times of in
not really mean in & out of the network 
""" 
acou_in_dimension_dict = {'bap': 1, 'mgc': 60, 'lf0': 1} 
acou_out_dimension_dict = {'bap': 3, 'vuv': 1, 'mgc': 180, 'lf0': 3}
# acou_in_dir_dict = {'bap': bap_dir, 'mgc': mgc_dir, 'lf0': lf0_dir}
acou_in_file_list_dict = {'bap': acou_bap_file_list, 'mgc': acou_mgc_file_list, 'lf0': acou_lf0_file_list}

In [92]:
acou_acoustic_worker = AcousticComposition(delta_win = delta_win, acc_win = acc_win)
acou_acoustic_worker.prepare_nn_data(acou_in_file_list_dict, acou_cmp_file_list, acou_in_dimension_dict, acou_out_dimension_dict)

KeyboardInterrupt: 

In [54]:
feat, num_frame = io_funcs.load_binary_file_frame(dur_cmp_file_list[2], 5)
print(feat.shape)
print(feat[0:10, :])
feat, num_frame = io_funcs.load_binary_file_frame(acou_cmp_file_list[2], 187)
print(feat.shape)
print(feat[0:10, :])

(131, 5)
[[ 13.  72. 166.   2.  54.]
 [  9.  47.   1.  54.  32.]
 [  1.  18.   4.   4.   4.]
 [  3. 100.   1.   2.   6.]
 [  4.   5.   3.   3.   3.]
 [  1.  32.   1.   1.   3.]
 [  5.   3.   2.   2.   3.]
 [  2.  26.   1.   5.   8.]
 [  2.   3.   3.   7.   6.]
 [  6.  77.  17.   5.   5.]]
(8640, 187)
[[ 0.          0.          0.         ...  0.0016107   0.01590419
   0.        ]
 [ 0.          0.          0.         ... -0.03265311  0.00975457
   0.        ]
 [ 0.          0.          0.         ...  0.00190853  0.00436544
   0.        ]
 ...
 [ 0.          0.          0.         ... -0.00899457 -0.00381122
   0.        ]
 [ 0.          0.          0.         ...  0.02834933 -0.01433814
   0.        ]
 [ 0.          0.          0.         ...  0.02132037 -0.0286779
   0.        ]]


## Remove silence phone

In [55]:
acou_silence_remover = SilenceRemover(n_cmp = acou_cmp_dim, silence_pattern = silence_pattern, remove_frame_features = True, subphone_feats = 'full')
acou_silence_remover.remove_silence(acou_cmp_file_list, orig_lab_file_list, acou_cmp_no_silence_file_list) 

In [56]:
_, num_frame = io_funcs.load_binary_file_frame(acou_cmp_file_list[2], 187)
_, num_frame_nn = io_funcs.load_binary_file_frame(acou_cmp_no_silence_file_list[2], 187)
print(num_frame)
print(num_frame_nn)

8640
7201


## Output feature (dim 187) normalization

In [57]:
acou_mvn_normaliser = MeanVarianceNorm(feature_dimension=acou_cmp_dim)
acou_global_mean_vector = acou_mvn_normaliser.compute_mean(acou_cmp_no_silence_file_list[0: acou_train_file_number], 0, acou_cmp_dim)
acou_global_std_vector = acou_mvn_normaliser.compute_std(acou_cmp_no_silence_file_list[0: acou_train_file_number], acou_global_mean_vector, 0, acou_cmp_dim)
acou_mvn_normaliser.feature_normalisation(acou_cmp_no_silence_file_list, acou_cmp_no_silence_norm_file_list)
acou_cmp_norm_info = np.concatenate((acou_global_mean_vector, acou_global_std_vector), axis=0)
acou_cmp_norm_info = np.array(acou_cmp_norm_info, 'float32')
fid = open(acou_cmp_norm_file, 'wb')
acou_cmp_norm_info.tofile(fid)
fid.close()

In [58]:
tmp1, num1 = io_funcs.load_binary_file_frame(acou_cmp_no_silence_file_list[0], 187)
tmp2, num2 = io_funcs.load_binary_file_frame(acou_cmp_no_silence_norm_file_list[0], 187)
print(num1 == num2)
print(tmp2[:, :4])

True
[[ 1.4198911  -0.69523036 -0.5961235   0.45662737]
 [ 1.1533878  -0.47438782  0.7849358   0.45662737]
 [ 1.2379152  -0.63909817 -0.92615116  0.45662737]
 ...
 [ 1.288423   -0.9105048  -0.6175857  -1.4407294 ]
 [ 0.9759231  -0.0580794   1.3470236  -1.5170972 ]
 [ 1.265789   -0.49311343 -1.7196321  -1.5170972 ]]


In [59]:
print(acou_cmp_norm_info.shape)
acou_global_std_vector

(2, 187)


array([[9.41241289, 1.80129955, 4.20871584, 0.22775437, 0.02732092,
        0.06407295, 1.52488712, 0.86403745, 0.74400974, 0.59257406,
        0.48412859, 0.3923912 , 0.30851035, 0.28519675, 0.36933757,
        0.41165707, 0.32822327, 0.28492896, 0.29147884, 0.25433476,
        0.20159926, 0.19080893, 0.15436258, 0.19601114, 0.19408261,
        0.21055441, 0.14320896, 0.11563111, 0.09560336, 0.10722646,
        0.11261904, 0.15451424, 0.13682862, 0.14987114, 0.14291312,
        0.10829363, 0.10096106, 0.08894939, 0.07560818, 0.07302475,
        0.08292949, 0.09943618, 0.1028903 , 0.09976558, 0.10206005,
        0.10056028, 0.08708021, 0.07575486, 0.06951946, 0.06276173,
        0.05988566, 0.06239593, 0.06657607, 0.06998015, 0.07346546,
        0.07865112, 0.08020094, 0.07525864, 0.06977282, 0.06375563,
        0.05756273, 0.05088478, 0.04439725, 0.04177266, 0.04052918,
        0.04215691, 0.23098677, 0.14314069, 0.10022263, 0.07618567,
        0.07058522, 0.06608377, 0.06079415, 0.05

In [60]:
acou_variance_file_dict = {'vuv': acou_vuv_var_file,
                           'mgc': acou_mgc_var_file,
                           'lf0': acou_lf0_var_file,
                           'bap': acou_bap_var_file}

In [61]:
feat_ind = 0
for feat in list(acou_out_dimension_dict.keys()):
    feat_std_vector = np.array(acou_global_std_vector[:, feat_ind: feat_ind + acou_out_dimension_dict[feat]], 'float32')
    fid = open(acou_variance_file_dict[feat], 'w')
    feat_var_vector = feat_std_vector**2
    feat_var_vector.tofile(fid)
    fid.close()
    feat_ind += acou_out_dimension_dict[feat]

## Model training

In [65]:
# TODO to implement cross-validation, print something here to see whether could do normalisation in Pytorch
batch_size = int(acou_train_file_number)
# batch_size = 1
print('batch_size: ' + str(batch_size))
acou_train_set = DurationDataset(acou_lab_no_silence_norm_file_list[:10], 
                                acou_cmp_no_silence_norm_file_list[:10], lab_dim=377, cmp_dim=187)
acou_valid_set = DurationDataset(acou_lab_no_silence_norm_file_list[acou_train_file_number: acou_train_file_number + acou_valid_file_number],
                                acou_cmp_no_silence_norm_file_list[acou_train_file_number: acou_train_file_number + acou_valid_file_number], lab_dim=377, cmp_dim=187)
acou_train_loader = data.DataLoader(acou_train_set, shuffle=True, batch_size=batch_size, collate_fn=collate_fn)
acou_valid_loader = data.DataLoader(acou_valid_set, shuffle=True, batch_size=acou_valid_file_number, collate_fn=collate_fn)

tmp = next(iter(dur_train_loader))
lab_, cmp_, _ = tmp
print(lab_.size())
print(cmp_.size())
print(len(Variable(lab_)))
print(len(dur_valid_set))

tmp = next(iter(acou_train_loader))
lab_, cmp_, sp_len = tmp
print(lab_.size())
print(cmp_.size())
print(len(Variable(lab_)))
print(len(acou_valid_set))
print(sp_len)

batch_size: 27


NameError: name 'dur_train_loader' is not defined

In [69]:
lr = 0.015
log_interval = 1
epochs = 50
acoustic_model = nn.Sequential(
    nn.Linear(acou_lab_dim, 300),
    nn.ReLU(),
    nn.Linear(300, acou_cmp_dim)
)
# acoustic_model = nn.Sequential(
#     nn.Linear(acou_lab_dim, 512),
#     nn.Dropout(0.5),
#     nn.ReLU(),
#     nn.Linear(512, 512),
#     nn.Dropout(0.5),
#     nn.ReLU(),
#     nn.Linear(512, 512),
#     nn.Dropout(0.5),
#     nn.ReLU(),
#     nn.Linear(512, acou_cmp_dim)
# )
optimizer = torch.optim.Adam(acoustic_model.parameters(), lr=lr)
criterion = F.mse_loss
for epoch in range(1, epochs+1):
    train(acoustic_model, acou_train_loader, acou_valid_loader, epoch)

/home/yongliang/venv3/lib/python3.5/site-packages/ipykernel_launcher.py:22: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.


Train Epoch: 1(0%)	Train Loss: 0.984347	Val Loss: 0.863277
Train Epoch: 2(0%)	Train Loss: 1.062275	Val Loss: 0.783125
Train Epoch: 3(0%)	Train Loss: 0.974228	Val Loss: 0.786081
Train Epoch: 4(0%)	Train Loss: 0.978735	Val Loss: 0.784810
Train Epoch: 5(0%)	Train Loss: 0.977458	Val Loss: 0.782597
Train Epoch: 6(0%)	Train Loss: 0.974964	Val Loss: 0.779685
Train Epoch: 7(0%)	Train Loss: 0.972507	Val Loss: 0.776630
Train Epoch: 8(0%)	Train Loss: 0.969165	Val Loss: 0.774019
Train Epoch: 9(0%)	Train Loss: 0.965468	Val Loss: 0.772322
Train Epoch: 10(0%)	Train Loss: 0.962575	Val Loss: 0.770879
Train Epoch: 11(0%)	Train Loss: 0.960082	Val Loss: 0.769364
Train Epoch: 12(0%)	Train Loss: 0.957539	Val Loss: 0.767490
Train Epoch: 13(0%)	Train Loss: 0.954855	Val Loss: 0.765427
Train Epoch: 14(0%)	Train Loss: 0.952160	Val Loss: 0.763440
Train Epoch: 15(0%)	Train Loss: 0.949404	Val Loss: 0.761820
Train Epoch: 16(0%)	Train Loss: 0.946651	Val Loss: 0.760525
Train Epoch: 17(0%)	Train Loss: 0.943908	Val Loss

In [68]:
lr = 0.1
log_interval = 1
epochs = 30
acoustic_model = DurationModel(acou_lab_dim, acou_cmp_dim)
print(acoustic_model)
optimizer = torch.optim.SGD(acoustic_model.parameters(), lr=lr)
criterion = F.mse_loss
for epoch in range(1, epochs+1):
    train(acoustic_model, acou_train_loader, acou_valid_loader, epoch)

DurationModel(
  (fc1): Linear(in_features=377, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=512, bias=True)
  (fc4): Linear(in_features=512, out_features=512, bias=True)
  (fc5): Linear(in_features=512, out_features=187, bias=True)
)


KeyboardInterrupt: 

In [85]:
acou_nn_mdl_file = os.path.join(acou_nn_mdl_dir, 'acou_nn_mdl.pt')
torch.save(acoustic_model.state_dict(), acou_nn_mdl_file)

# Synthesis

In [71]:
synth_id_list = file_id_list[-dur_test_file_number:]
input_lab_file_list = orig_lab_file_list[-dur_test_file_number:]

synth_dir = os.path.join(exp_dir, 'synth')
if not os.path.exists(synth_dir):
    os.makedirs(synth_dir)
    
wav_dir = os.path.join(synth_dir, 'wav')
if not os.path.exists(wav_dir):
    os.makedirs(wav_dir)
    
synth_inter_dir = os.path.join(synth_dir, 'inter')
if not os.path.exists(synth_inter_dir):
    os.makedirs(synth_inter_dir)
    
synth_dur_lab_norm_dir = os.path.join(synth_inter_dir, 'dur_lab_norm')
if not os.path.exists(synth_dur_lab_norm_dir):
    os.makedirs(synth_dur_lab_norm_dir)
    
synth_dur_cmp_pred_dir = os.path.join(synth_inter_dir, 'dur_cmp_pred')
if not os.path.exists(synth_dur_cmp_pred_dir):
    os.makedirs(synth_dur_cmp_pred_dir)
    
synth_dur_lab_file_list = gen_file_list(dur_lab_dir, synth_id_list, 'labbin')
synth_dur_lab_norm_file_list = gen_file_list(synth_dur_lab_norm_dir, synth_id_list, 'labbin')
synth_dur_cmp_pred_file_list = gen_file_list(synth_dur_cmp_pred_dir, synth_id_list, 'cmp')




orig_lab_file_list = get_file_list_of_dir(lab_dir)
file_id_list = get_file_id_list(orig_lab_file_list)
dur_lab_file_list = gen_file_list(dur_lab_dir, file_id_list, 'labbin')
dur_lab_no_silence_file_list = gen_file_list(dur_lab_no_silence_dir, file_id_list, 'labbin')
dur_lab_no_silence_norm_file_list = gen_file_list(dur_lab_no_silence_norm_dir, file_id_list, 'labbin')
dur_dur_file_list = gen_file_list(dur_dur_dir, file_id_list, 'dur')
dur_cmp_file_list = gen_file_list(dur_cmp_dir, file_id_list, 'cmp')
dur_cmp_no_silence_file_list = gen_file_list(dur_cmp_no_silence_dir, file_id_list, 'cmp')
dur_cmp_no_silence_norm_file_list = gen_file_list(dur_cmp_no_silence_norm_dir, file_id_list, 'cmp')

synth_acou_lab_norm_dir = os.path.join(synth_inter_dir, 'acou_lab_norm')
if not os.path.exists(synth_acou_lab_norm_dir):
    os.makedirs(synth_acou_lab_norm_dir)
    
synth_acou_cmp_pred_dir = os.path.join(synth_inter_dir, 'acou_cmp_pred')
if not os.path.exists(synth_acou_cmp_pred_dir):
    os.makedirs(synth_acou_cmp_pred_dir)
    
synth_acou_lab_file_list = gen_file_list(synth_acou_lab_norm_dir, synth_id_list, 'labbin')
synth_acou_lab_norm_file_list = gen_file_list(synth_acou_lab_norm_dir, synth_id_list, 'labbin')
synth_acou_cmp_pred_file_list = gen_file_list(synth_acou_cmp_pred_dir, synth_id_list, 'cmp')


## Normalize label files for duration model (silence not removed)

In [72]:
synth_dur_lab_normaliser = MinMaxNormalisation(feature_dimension = dur_lab_dim, min_value = 0.01, max_value = 0.99)
synth_dur_lab_normaliser.load_min_max_values(dur_lab_norm_file)
synth_dur_lab_normaliser.normalise_data(synth_dur_lab_file_list, synth_dur_lab_norm_file_list)

In [73]:
tmp1, num1 = io_funcs.load_binary_file_frame(synth_dur_lab_norm_file_list[0], 368)
tmp2, num2 = io_funcs.load_binary_file_frame(synth_dur_lab_file_list[0], 368)
print(synth_dur_lab_norm_file_list[0])
print('num1: ', str(num1))
print('num2: ', str(num2))
# print(tmp1[0: 10, :])
# print(synth_dur_lab_norm_file_list[0])

/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/inter/dur_lab_norm/nitech_jp_song070_f001_070.labbin
num1:  55
num2:  55


## Predict durations

In [74]:
synth_duration_model = DurationModel(dur_lab_dim, dur_cmp_dim)
synth_duration_model.load_state_dict(torch.load(dur_nn_mdl_file))
synth_duration_model.eval()

NameError: name 'dur_nn_mdl_file' is not defined

In [75]:
lab, num_frame = io_funcs.load_binary_file_frame(synth_dur_lab_norm_file_list[0], 368)
lab = torch.from_numpy(lab)
lab = lab[None, :, :]
dur_cmp_pred = synth_duration_model(lab)
dur_cmp_pred = dur_cmp_pred.detach().numpy()[0]
dur_cmp_pred

array([[ 0.01988075, -0.0144904 , -0.00999507,  0.01847764, -0.04645242],
       [ 0.02036698, -0.01061654, -0.01343583,  0.0174404 , -0.04564231],
       [ 0.01980831, -0.01042566, -0.00955306,  0.01998632, -0.0467877 ],
       [ 0.02019942, -0.01023069, -0.01224981,  0.01947055, -0.05132477],
       [ 0.01836238, -0.0113967 , -0.01231135,  0.02014951, -0.04862119],
       [ 0.01882902, -0.00813174, -0.01518269,  0.02333031, -0.04627261],
       [ 0.021107  , -0.00600657, -0.01176079,  0.0198276 , -0.04381986],
       [ 0.0204055 , -0.01126596, -0.00851345,  0.02269961, -0.04616012],
       [ 0.02336671, -0.01064226, -0.00915501,  0.01942649, -0.05331106],
       [ 0.0211011 , -0.01066624, -0.00971396,  0.01897801, -0.05050771],
       [ 0.02177164, -0.0063715 , -0.01332739,  0.02292496, -0.0482948 ],
       [ 0.01991749, -0.01176413, -0.00958858,  0.022183  , -0.04780466],
       [ 0.02152749, -0.00871838, -0.0094396 ,  0.01820032, -0.04883516],
       [ 0.02160495, -0.00902334, -0.0

## Denormalization

In [76]:
fid = open(dur_cmp_norm_file, 'rb')
dur_cmp_norm_info = np.fromfile(fid, dtype=np.float32)
fid.close()
dur_cmp_norm_info = dur_cmp_norm_info.reshape(2, -1)
dur_cmp_mean = dur_cmp_norm_info[0, ]
dur_cmp_std = dur_cmp_norm_info[1, ]

print(synth_dur_cmp_pred_file_list[0])

io_funcs.array_to_binary_file(dur_cmp_pred, synth_dur_cmp_pred_file_list[0])

print(dur_cmp_mean)
print(dur_cmp_std)

/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/inter/dur_cmp_pred/nitech_jp_song070_f001_070.cmp
[ 5.4560676 16.22251   14.50423    9.729328   5.6103916]
[ 4.778163  32.451237  30.338848  25.81974    6.8933287]


In [77]:
synth_dur_denormaliser = MeanVarianceNorm(feature_dimension=dur_cmp_dim)
synth_dur_denormaliser.feature_denormalisation(synth_dur_cmp_pred_file_list, synth_dur_cmp_pred_file_list, dur_cmp_mean, dur_cmp_std)
dur_cmp_pred, _ = io_funcs.load_binary_file_frame(synth_dur_cmp_pred_file_list[0], 5)
print(dur_cmp_pred[:10, :])

[[ 5.551061  15.752278  14.200991  10.206416   5.2901797]
 [ 5.5533843 15.87799   14.0966015 10.179635   5.295764 ]
 [ 5.550715  15.884184  14.2144    10.24537    5.2878685]
 [ 5.5525837 15.890511  14.132585  10.232053   5.256593 ]
 [ 5.543806  15.852673  14.130717  10.249583   5.27523  ]
 [ 5.546036  15.958624  14.043604  10.331711   5.2914195]
 [ 5.55692   16.027588  14.147421  10.241272   5.3083267]
 [ 5.5535684 15.856915  14.245941  10.315426   5.292195 ]
 [ 5.5677176 15.877155  14.226478  10.230915   5.242901 ]
 [ 5.556892  15.876377  14.209519  10.219336   5.262225 ]]


## Change original label files with newly predicted durations

In [78]:
from frontend.parameter_generation import ParameterGeneration
from frontend.label_modifier import HTSLabelModification
synth_dur_extention_dict = {'dur': '.dur'}
synth_dur_out_dimension_dict = {'dur': 5}
synth_dur_cmp_dim = 5


synth_dur_list = [os.path.splitext(synth_dur_cmp_pred_file_list[0])[0] + synth_dur_extention_dict['dur']]
synth_lab_list = [os.path.splitext(synth_dur_cmp_pred_file_list[0])[0] + '.lab']
print(synth_dur_list)
print(synth_lab_list)

synth_decomposer = ParameterGeneration(['mgc', 'bap', 'lf0'])
synth_decomposer.duration_decomposition(synth_dur_cmp_pred_file_list, synth_dur_cmp_dim, synth_dur_out_dimension_dict, synth_dur_extention_dict)
synth_label_modifier = HTSLabelModification(silence_pattern = silence_pattern)
synth_label_modifier.modify_duration_labels(input_lab_file_list, synth_dur_list, synth_lab_list)

['/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/inter/dur_cmp_pred/nitech_jp_song070_f001_070.dur']
['/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/inter/dur_cmp_pred/nitech_jp_song070_f001_070.lab']


## Normalize label files for acoustic model (silence not removed)

In [79]:
synth_acou_lab_normaliser = HTSLabelNormalisation(question, add_frame_features=True, subphone_feats='full')
synth_acou_lab_normaliser.perform_normalisation(synth_lab_list, synth_acou_lab_file_list)
synth_acou_lab_normaliser = MinMaxNormalisation(feature_dimension = acou_lab_dim, min_value = 0.01, max_value = 0.99)
synth_acou_lab_normaliser.load_min_max_values(acou_lab_norm_file)
synth_acou_lab_normaliser.normalise_data(synth_acou_lab_file_list, synth_acou_lab_norm_file_list)

## Predict acoustic features

In [86]:
synth_acoustic_model = DurationModel(acou_lab_dim, acou_cmp_dim)
synth_acoustic_model.load_state_dict(torch.load(acou_nn_mdl_file))
synth_acoustic_model.eval()

RuntimeError: Error(s) in loading state_dict for DurationModel:
	Missing key(s) in state_dict: "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias", "fc3.weight", "fc3.bias", "fc4.weight", "fc4.bias", "fc5.weight", "fc5.bias". 
	Unexpected key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias". 

In [88]:
lab, num_frame = io_funcs.load_binary_file_frame(synth_acou_lab_norm_file_list[0], 377)
lab = torch.from_numpy(lab)
lab = lab[None, :, :]
acou_cmp_pred = synth_acoustic_model(lab)
acou_cmp_pred = acou_cmp_pred.detach().numpy()[0]
acou_cmp_pred.shape

(3216, 187)

## Denormalization

In [89]:
fid = open(acou_cmp_norm_file, 'rb')
acou_cmp_norm_info = np.fromfile(fid, dtype=np.float32)
fid.close()
acou_cmp_norm_info = acou_cmp_norm_info.reshape(2, -1)
acou_cmp_mean = acou_cmp_norm_info[0, ]
acou_cmp_std = acou_cmp_norm_info[1, ]

print(synth_acou_cmp_pred_file_list[0])


io_funcs.array_to_binary_file(acou_cmp_pred, synth_acou_cmp_pred_file_list[0])

print(acou_cmp_mean)
print(acou_cmp_std)

/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/inter/acou_cmp_pred/nitech_jp_song070_f001_070.cmp
[-1.33646011e+01 -1.90148572e-03  4.75082546e-04  5.96542645e+00 -3.50371033e-06 -1.21180547e-05  5.07352877e+00  1.88283157e+00 -2.73135006e-01  1.37185544e-01 -4.23395693e-01  2.41781697e-01 -2.04522818e-01 -4.18005884e-02  3.96365196e-01 -1.26078025e-01  3.74176562e-01 -1.93812922e-01 -3.76398936e-02 -1.38404528e-02 -5.09452028e-03  1.28273636e-01 -1.30870998e-01  8.73090476e-02 -2.49601901e-03 -8.83054454e-03 -3.25787514e-02 -2.69498564e-02  2.26364378e-02 -5.02169877e-02  4.38574776e-02 -4.56125587e-02  2.92196702e-02 -3.07271220e-02  2.09769118e-03  2.67485492e-02 -4.82758544e-02  5.80238625e-02 -5.66445962e-02  4.08596694e-02 -1.98573247e-02  4.57508303e-03 -4.61094460e-04 -1.20418239e-03  1.06062898e-02 -2.40169801e-02  2.86857504e-02 -2.29858626e-02  1.30661651e-02 -4.51678643e-03 -4.03065840e-03  1.32622905e-02 -2.11629681e-02  2.48682052e-02 -1.93230826e-0

In [90]:
synth_acou_denormaliser = MeanVarianceNorm(feature_dimension=acou_cmp_dim)
synth_acou_denormaliser.feature_denormalisation(synth_acou_cmp_pred_file_list, synth_acou_cmp_pred_file_list, acou_cmp_mean, acou_cmp_std)
dur_cmp_pred, _ = io_funcs.load_binary_file_frame(synth_acou_cmp_pred_file_list[0], 187)
print(dur_cmp_pred[:10, :10])

[[-1.38575516e+01  1.01585373e-01 -5.46068065e-02  5.96189833e+00  6.89454260e-04 -2.46225647e-03  5.09212208e+00  1.87044120e+00 -2.88518071e-01  1.22004353e-01]
 [-1.38563013e+01  1.00108132e-01 -5.43414243e-02  5.96184349e+00  6.82886865e-04 -2.47346167e-03  5.09386969e+00  1.86894822e+00 -2.89718211e-01  1.22529343e-01]
 [-1.38563023e+01  1.00061432e-01 -5.43866716e-02  5.96184492e+00  6.82633079e-04 -2.47423304e-03  5.09383392e+00  1.86895490e+00 -2.89702773e-01  1.22511789e-01]
 [-1.38563204e+01  1.00020953e-01 -5.44308163e-02  5.96184683e+00  6.82366954e-04 -2.47490872e-03  5.09380102e+00  1.86896157e+00 -2.89689153e-01  1.22494146e-01]
 [-1.38563423e+01  9.99839976e-02 -5.44703752e-02  5.96184874e+00  6.82100654e-04 -2.47563026e-03  5.09376812e+00  1.86896980e+00 -2.89676309e-01  1.22475892e-01]
 [-1.38563643e+01  9.99474004e-02 -5.45096397e-02  5.96185064e+00  6.81819394e-04 -2.47638649e-03  5.09373426e+00  1.86897981e+00 -2.89664090e-01  1.22457244e-01]
 [-1.38563890e+01  9.9

In [91]:
synth_acou_extention_dict = {'lf0': '.lf0', 'mgc': '.mgc', 'bap': '.bap'}
synth_acou_out_dimension_dict = {'lf0': 3, 'mgc': 180, 'bap': 3, 'vuv': 1}
synth_acou_cmp_dim = 187


# synth_dur_list = [os.path.splitext(synth_dur_cmp_pred_file_list[0])[0] + synth_dur_extention_dict['dur']]
# synth_lab_list = [os.path.splitext(synth_dur_cmp_pred_file_list[0])[0] + '.lab']
# print(synth_dur_list)
# print(synth_lab_list)

synth_decomposer = ParameterGeneration(['mgc', 'bap', 'lf0'])

synth_decomposer.acoustic_decomposition(synth_acou_cmp_pred_file_list, synth_acou_cmp_dim, synth_acou_out_dimension_dict, synth_acou_extention_dict, acou_variance_file_dict,True)



In [93]:
## copy features to wav
for file in synth_acou_cmp_pred_file_list:
    base = os.path.splitext(file)[0]
    for ext in (['.mgc', '.bap', '.lf0']):
        feat_file = base + ext
        copy(feat_file, wav_dir)

## Synthesize wav

In [94]:
def run_process(args,log=True):
    logger = logging.getLogger("subprocess")

    # a convenience function instead of calling subprocess directly
    # this is so that we can do some logging and catch exceptions

    # we don't always want debug logging, even when logging level is DEBUG
    # especially if calling a lot of external functions
    # so we can disable it by force, where necessary
    if log:
        logger.debug('%s' % args)

    try:
        # the following is only available in later versions of Python
        # rval = subprocess.check_output(args)

        # bufsize=-1 enables buffering and may improve performance compared to the unbuffered case
        p = subprocess.Popen(args, bufsize=-1, shell=True,
                        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                        close_fds=True, env=os.environ)
        # better to use communicate() than read() and write() - this avoids deadlocks
        (stdoutdata, stderrdata) = p.communicate()

        if p.returncode != 0:
            # for critical things, we always log, even if log==False
            logger.critical('exit status %d' % p.returncode )
            logger.critical(' for command: %s' % args )
            logger.critical('      stderr: %s' % stderrdata )
            logger.critical('      stdout: %s' % stdoutdata )
            raise OSError

        return (stdoutdata, stderrdata)

    except subprocess.CalledProcessError as e:
        # not sure under what circumstances this exception would be raised in Python 2.6
        logger.critical('exit status %d' % e.returncode )
        logger.critical(' for command: %s' % args )
        # not sure if there is an 'output' attribute under 2.6 ? still need to test this...
        logger.critical('  output: %s' % e.output )
        raise

    except ValueError:
        logger.critical('ValueError for %s' % args )
        raise

    except OSError:
        logger.critical('OSError for %s' % args )
        raise

    except KeyboardInterrupt:
        logger.critical('KeyboardInterrupt during %s' % args )
        try:
            # try to kill the subprocess, if it exists
            p.kill()
        except UnboundLocalError:
            # this means that p was undefined at the moment of the keyboard interrupt
            # (and we do nothing)
            pass

        raise KeyboardInterrupt


In [95]:
import pickle
with open('/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/test/cfg.pkl', 'rb') as f:
    cfg = pickle.load(f)

In [96]:
def wavgen_straight_type_vocoder(gen_dir, file_id_list, logger):
    '''
    Waveform generation with STRAIGHT or WORLD vocoders.
    (whose acoustic parameters are: mgc, bap, and lf0)
    '''

    pf_coef = 1.4
    fw_coef = 0.58
    co_coef = 511
    fl_coef = 1024
    mgc_dim = 60
    fw_alpha = 0.58
    sr = 16000
    fl = 1024



    counter=1
    max_counter = len(file_id_list)


    for filename in file_id_list:

        logger.info('creating waveform for %4d of %4d: %s' % (counter,max_counter,filename) )
        counter=counter+1
        base   = filename
        files = {'sp'  : base + '.sp',
                 'mgc' : base + '.mgc',
                 'f0'  : base + '.f0',
                 'lf0' : base + '.lf0',
                 'ap'  : base + '.ap',
                 'bap' : base + '.bap',
                 'wav' : base + '.wav'}

        mgc_file_name = files['mgc']
        bap_file_name = files['bap']

        cur_dir = os.getcwd()
        os.chdir(gen_dir)


        mgc_file_name = files['mgc']+'_p_mgc'
        post_filter(files['mgc'], mgc_file_name, mgc_dim, pf_coef, fw_coef, co_coef, fl_coef, gen_dir, SPTK)





        run_process('{sopr} -magic -1.0E+10 -EXP -MAGIC 0.0 {lf0} | {x2x} +fd > {f0}'.format(sopr=SPTK['SOPR'], lf0=files['lf0'], x2x=SPTK['X2X'], f0=files['f0']))

        run_process('{sopr} -c 0 {bap} | {x2x} +fd > {ap}'.format(sopr=SPTK['SOPR'],bap=files['bap'],x2x=SPTK['X2X'],ap=files['ap']))


        run_process('{mgc2sp} -a {alpha} -g 0 -m {order} -l {fl} -o 2 {mgc} | {sopr} -d 32768.0 -P | {x2x} +fd > {sp}'
                        .format(mgc2sp=SPTK['MGC2SP'], alpha=fw_alpha, order=mgc_dim-1, fl=fl, mgc=mgc_file_name, sopr=SPTK['SOPR'], x2x=SPTK['X2X'], sp=files['sp']))

        run_process('{synworld} {fl} {sr} {f0} {sp} {ap} {wav}'
                         .format(synworld=WORLD['SYNTHESIS'], fl=fl, sr=sr, f0=files['f0'], sp=files['sp'], ap=files['ap'], wav=files['wav']))

#         run_process('rm -f {ap} {sp} {f0}'.format(ap=files['ap'],sp=files['sp'],f0=files['f0']))

        os.chdir(cur_dir)

In [97]:
def post_filter(mgc_file_in, mgc_file_out, mgc_dim, pf_coef, fw_coef, co_coef, fl_coef, gen_dir, SPTK):


    line = "echo 1 1 "
    for i in range(2, mgc_dim):
        line = line + str(pf_coef) + " "

    run_process('{line} | {x2x} +af > {weight}'
                .format(line=line, x2x=SPTK['X2X'], weight=os.path.join(gen_dir, 'weight')))

    run_process('{freqt} -m {order} -a {fw} -M {co} -A 0 < {mgc} | {c2acr} -m {co} -M 0 -l {fl} > {base_r0}'
                .format(freqt=SPTK['FREQT'], order=mgc_dim-1, fw=fw_coef, co=co_coef, mgc=mgc_file_in, c2acr=SPTK['C2ACR'], fl=fl_coef, base_r0=mgc_file_in+'_r0'))

    run_process('{vopr} -m -n {order} < {mgc} {weight} | {freqt} -m {order} -a {fw} -M {co} -A 0 | {c2acr} -m {co} -M 0 -l {fl} > {base_p_r0}'
                .format(vopr=SPTK['VOPR'], order=mgc_dim-1, mgc=mgc_file_in, weight=os.path.join(gen_dir, 'weight'),
                        freqt=SPTK['FREQT'], fw=fw_coef, co=co_coef,
                        c2acr=SPTK['C2ACR'], fl=fl_coef, base_p_r0=mgc_file_in+'_p_r0'))

    run_process('{vopr} -m -n {order} < {mgc} {weight} | {mc2b} -m {order} -a {fw} | {bcp} -n {order} -s 0 -e 0 > {base_b0}'
                .format(vopr=SPTK['VOPR'], order=mgc_dim-1, mgc=mgc_file_in, weight=os.path.join(gen_dir, 'weight'),
                        mc2b=SPTK['MC2B'], fw=fw_coef,
                        bcp=SPTK['BCP'], base_b0=mgc_file_in+'_b0'))

    run_process('{vopr} -d < {base_r0} {base_p_r0} | {sopr} -LN -d 2 | {vopr} -a {base_b0} > {base_p_b0}'
                .format(vopr=SPTK['VOPR'], base_r0=mgc_file_in+'_r0', base_p_r0=mgc_file_in+'_p_r0',
                        sopr=SPTK['SOPR'],
                        base_b0=mgc_file_in+'_b0', base_p_b0=mgc_file_in+'_p_b0'))

    run_process('{vopr} -m -n {order} < {mgc} {weight} | {mc2b} -m {order} -a {fw} | {bcp} -n {order} -s 1 -e {order} | {merge} -n {order2} -s 0 -N 0 {base_p_b0} | {b2mc} -m {order} -a {fw} > {base_p_mgc}'
                .format(vopr=SPTK['VOPR'], order=mgc_dim-1, mgc=mgc_file_in, weight=os.path.join(gen_dir, 'weight'),
                        mc2b=SPTK['MC2B'],  fw=fw_coef,
                        bcp=SPTK['BCP'],
                        merge=SPTK['MERGE'], order2=mgc_dim-2, base_p_b0=mgc_file_in+'_p_b0',
                        b2mc=SPTK['B2MC'], base_p_mgc=mgc_file_out))

    return

In [98]:
## copy features to wav
for file in synth_acou_cmp_pred_file_list:
    base = os.path.splitext(file)[0]
    for ext in (['.mgc', '.bap', '.lf0']):
        feat_file = base + ext
        copy(feat_file, wav_dir)

In [99]:
logger = logging.getLogger("wav_generation")
wavgen_straight_type_vocoder(wav_dir, synth_id_list, logger)
print(wav_dir)
print(synth_id_list)

/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/wav
['nitech_jp_song070_f001_070']


# TEST

In [161]:
my_cmp_norm_info_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/acoustic_model/inter/cmp_norm_187.dat'
ml_cmp_norm_info_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s1/experiments/acoustic_model/inter_module/norm_info__mgc_lf0_vuv_bap_187_MVN.dat'

fid = open(my_cmp_norm_info_file, 'rb')
my_cmp_norm_info = np.fromfile(fid, dtype=np.float32)
fid.close()
my_cmp_norm_info = my_cmp_norm_info.reshape(2, -1)
my_cmp_mean = my_cmp_norm_info[0, ]
my_cmp_std = my_cmp_norm_info[1, ]

fid = open(ml_cmp_norm_info_file, 'rb')
ml_cmp_norm_info = np.fromfile(fid, dtype=np.float32)
fid.close()
ml_cmp_norm_info = ml_cmp_norm_info.reshape(2, -1)
ml_cmp_mean = ml_cmp_norm_info[0, ]
ml_cmp_std = ml_cmp_norm_info[1, ]

print(my_cmp_mean.all() == ml_cmp_mean.all())
print(my_cmp_std.all() == ml_cmp_std.all())

True
True


In [169]:
my_cmp_no_silence_norm_file = acou_cmp_no_silence_norm_file_list[0]
ml_cmp_no_silence_norm_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s1/experiments/acoustic_model/inter_module/nn_norm_mgc_lf0_vuv_bap_187/nitech_jp_song070_f001_003.cmp'
my_cmp_no_silence_norm, my_n_frame = io_funcs.load_binary_file_frame(my_cmp_no_silence_norm_file, 187)
ml_cmp_no_silence_norm, ml_n_frame = io_funcs.load_binary_file_frame(ml_cmp_no_silence_norm_file, 187)
print(my_n_frame == ml_n_frame)
print(my_cmp_no_silence_norm.all() == ml_cmp_no_silence_norm.all())

my_lab_no_silence_norm_file = acou_lab_no_silence_norm_file_list[0]
ml_lab_no_silence_norm_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s1/experiments/acoustic_model/inter_module/nn_no_silence_lab_norm_377/nitech_jp_song070_f001_003.lab'
my_lab_no_silence_norm, my_n_frame = io_funcs.load_binary_file_frame(my_lab_no_silence_norm_file, 377)
ml_lab_no_silence_norm, ml_n_frame = io_funcs.load_binary_file_frame(ml_lab_no_silence_norm_file, 377)
print(my_n_frame == ml_n_frame)
print(my_lab_no_silence_norm.all() == ml_lab_no_silence_norm.all())

True
True
True
True


In [173]:
test_cmp_no_silence_norm_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/acoustic_model/inter/cmp_no_silence_norm_187/nitech_jp_song070_f001_003.cmp'
test_cmp_file_list = [test_cmp_no_silence_norm_file]
test_cmp_no_silence_pred_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/test/nitech_jp_song070_f001_003.cmp'
test_denorm_file_list = [test_cmp_no_silence_pred_file]

synth_acou_denormaliser = MeanVarianceNorm(feature_dimension=acou_cmp_dim)
synth_acou_denormaliser.feature_denormalisation(test_cmp_file_list, test_denorm_file_list, acou_cmp_mean, acou_cmp_std)

synth_decomposer.acoustic_decomposition(test_denorm_file_list, synth_acou_cmp_dim, synth_acou_out_dimension_dict, synth_acou_extention_dict, acou_variance_file_dict,True)
wavgen_straight_type_vocoder('/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/test/', ['nitech_jp_song070_f001_003'], logger)

In [ ]:
f0_file = os.path.join(wav_dir, 'nitech_jp_song070_f001_070.f0')
mgc_file = '/home/yongliang/third_party/merlin/egs/singing_synthesis/s3/exp/synth/inter/acou_cmp_pred/nitech_jp_song070_f001_070.mgc'
f0, n_frame = io_funcs.load_binary_file_frame(f0_file, 1)
mgc, n_frame2 = io_funcs.load_binary_file_frame(mgc_file, 60)
print(n_frame)
print(n_frame2)

# PITCH MODEL